### ISSUE TITLE
Registration Form

### ISSUE THREAD

**Issue by saurabhsunil95** [morphosis-nitmz/CTF-19#2]

**Comment by abhi1d** [comment]
registration for the new user: matching the password phase, if a new user registers then automatically redirect to the login page.

**Comment by saurabhsunil95** [comment]
Done both task.
Password matching done and if Password and ConfirmPassword column not matched then it automatically redirect to registation page with errorMessage.

`http.authorizeRequests()
				.antMatchers("/registrationPage*").permitAll()
				.antMatchers("/Register*").permitAll()
				.anyRequest().authenticated()
			.and()
				.formLogin()
					.loginPage("/showMyLoginPage")
					.loginProcessingUrl("/authenticateTheUser")
					.permitAll()
				.and()
					.logout().permitAll();`

**Comment by saurabhsunil95** [comment]
With the help of `.anyMatchers` access of Register.java servlet done.
