### ISSUE TITLE
User database Creation

### ISSUE THREAD

**Issue by abhi1d** [morphosis-nitmz/CTF-19#3]
User database creation dynamically, when new user registers.

**Comment by saurabhsunil95** [comment]
Done.
table:- **ques_id** and **flag** columns.
Table gets dynamically created  after registration.

**Comment by saurabhsunil95** [comment]
We have to care about **flag** , suppose Ans of any question correctly submitted by any user then flag become 1 but after that if user submit wrong ans of same question then we have to care about flag (means its value not change 1 to 0) because user already submitted correct ans.
